on: push
name: ğŸš€ Deploy website on push
jobs:
  web-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Get latest code
      uses: actions/checkout@v2
    
    - name: ğŸ¡ Setup PHP
      uses: shivammathur/setup-php@v2
      with:
          php-version: 8.0
          extensions: mbstring, dom, fileinfo
          coverage: xdebug

    - name: ğŸ•¹ï¸ Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      
    - name: ğŸ“š Install Dependencies
      run: composer install --prefer-dist
      
    - name: ğŸ« Generate key
      run: php artisan key:generate
      
    - name: ğŸ‘® Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
